Feature eslint fix violations
3dmol/3Dmol.js pull request #577
Opened 2022-03-23 22:42 UTC by angel4576

# Description

- Fixed all ESLint violations for most of the js files
- Configured ESLint rules in .eslintrc.json
- Added .eslintignore to make ESLint ignore some files.  
#567 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
`npm run build`

**My Configuration**:
* `npm --version`: 8.3.1
* `node --version`: v16.14.0
* `python3 --version`: 3.10.0
* OS: Windows
* ARCH: x86_64

2022-03-27 20:52 UTC, dkoes commented
Checks need to pass before this can be considered for merging.

2022-03-29 01:42 UTC, tjakubiec218 approved these changes

2022-03-29 14:36 UTC, dkoes requested changes
I went through one not very large file (3dmol.js) and found at least two breaking changes.  This does not inspire confidence.  I think perhaps large scale changes like this should wait until there is greater code coverage with the tests.  It does not help that there appear to be some changes made that aren't required by eslint, which just results in more diffs to review.

In any case, eslint should be run as part of the build process.  There are currently
✖ 19676 problems (11196 errors, 8480 warnings)
This PR cannot be merged until those are zero.

I'd recommend reducing the scope of the linting to just the eslint recommended rules, or an even smaller subset (e.g. disable the suggestions).  Once the system is integrated into the build it will be easy enough to incrementally enable rules.

2022-03-29 14:36 UTC, dkoes commented on 3Dmol/3dmol.js
> +    xmin = xmin < atom.x ? xmin : atom.x;
what eslint rule is requiring clarifying parentheses be removed?  as far as I can tell, it doesn't mind so why were these changes made?

2022-03-29 14:36 UTC, dkoes commented on 3Dmol/3dmol.js
> +  const viewers = $3Dmol.createViewerGrid(element, {rows: 1, cols: 2, controlAll: true});
no API changes

2022-03-29 19:40 UTC, angel4576 commented on 3Dmol/3dmol.js
> -if ( typeof module === "object" && typeof module.exports === "object" ) {
Hello professor, the option for eqeqeq rule is set to "smart", which enforces the use of === and !== except for comparing two literal values, evaluating typeof values, and comparing with null

2022-03-29 19:49 UTC, angel4576 commented on 3Dmol/3dmol.js
> - * @param {Object} shared_viewer_resources shared resources between viewers' renderers
I can fix that. Sorry about that

2022-09-04 11:26 UTC, gncs commented
Using a linter like ESLint is an excellent idea in my opinion and I highly appreciate @angel4576 effort to introduce a consistent style to the project. At the same time, I understand @dkoes 's concern that other API and potentially behavioral changes were introduced in this PR.

As projects typically benefit from a consistent code style and adherence to best practices, I encourage the use of a linter. One could consider restarting this PR - maybe with a more minimalist linter config. As @dkoes said, one can always make the linter stricter or more pedantic later on.

What are your thoughts?

2022-09-06 12:11 UTC, dkoes commented
@RyanGuild  is in the middle of a massive refactor that will convert all of 3Dmol.js to typescript with an updated build system that includes linting.  Hence all the merge conflicts.

2022-09-06 12:11 UTC, closed without merging

2022-09-07 21:14 UTC, gncs commented
Exciting, thank you for your efforts.

2022-09-24 10:58 UTC, GermaVinsmoke commented
@dkoes By when we can expect to see the new Typescript change? Interested to contribute.

2022-09-28 14:52 UTC, GermaVinsmoke commented
I see. Maybe I can go through the typescript branches created by @RyanGuild and see what I can do 🤔

2022-09-28 14:53 UTC, dkoes commented
That would be fantastic!

2022-09-28 17:43 UTC, GermaVinsmoke commented
It looks like, he was trying to add **rollup** first but then he stopped. Can be seen in [feature-modules](https://github.com/3dmol/3Dmol.js/tree/feature-modules) branch. Later on, he decided to use Parcel as a bundler.

Some of the branches which are not merged in the master are (Correct me if I'm wrong) -
- [tsport-partial-charges](https://github.com/3dmol/3Dmol.js/tree/tsport-partial-charges)
- [tsport-marchingcube](https://github.com/3dmol/3Dmol.js/tree/tsport-marchingcube)
- [tsport-webgl](https://github.com/3dmol/3Dmol.js/tree/tsport-webgl)
- [tsport-parsers](https://github.com/3dmol/3Dmol.js/tree/tsport-parsers)

I think we need to first see what all changes were made in these branches and whether these are even needed or not. Too much work! 😬