[Feat] - Performance Improvements to `GLDraw.ts`, `GLCartoon.ts`, `GLModel.ts`
3dmol/3Dmol.js pull request #662
Opened 2023-03-23 15:28 UTC by adithyaakrishna

**Description:**

- This PR is Related to #661 - Optimized GLDraw.ts
- This PR is Related to #661 - Optimized GLCartoon.ts
- This PR is Related to #661 - Optimized GLModel.ts

2023-03-23 16:07 UTC, adithyaakrishna commented
@dkoes I'm trying to figure out why the CI is failing here, but wasn't able to. Could you please help me with this or suggest what needs to be done?

2023-03-23 16:42 UTC, dkoes commented
Is `npm test` not failing in your local checkout?

2023-03-23 16:44 UTC, adithyaakrishna commented
@dkoes Figured it out, it's an issue with `.set()` functions which I added for Arrays. They are mostly [Float32Arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array) and I don't think the `set()` works with them, I will send a fix for that :)

2023-03-23 17:40 UTC, adithyaakrishna commented
I think the set() methods are working fine, but its something related to TS and Node/NPM

@dkoes The tests are failing on the master branch for me :(

Around 18 tests are failing not sure why and this is the error which I am getting for all of them,

<img width="1175" alt="Screenshot 2023-03-23 at 11 09 13 PM" src="https://user-images.githubusercontent.com/23498248/227293059-e841f448-62ef-4cf7-a81d-5828ac727990.png">

2023-03-24 05:15 UTC, adithyaakrishna commented
@dkoes I found the issue to be my system itself, its based on arm architecture and node-canvas does not support prebuilt binaries for this architecture. I will continue to update the codebase based on perf improvements. I have a secondary PC which used intel x86_x64 architecture in which I can run the tests and check where it is breaking down :)

2023-06-13 13:30 UTC, dkoes requested changes
I am never going to approve this PR.  There are too many changes and too many of them would introduce regressions.  I suggest starting over.  Only make a change if you can prove it is actually an improvement and provide the proof in the PR.  There should not be one single "performance improvement" PR, but separate PRs for each issue addressed. (e.g. use of Math.hypot at all relevant places)

2023-06-13 13:30 UTC, dkoes commented on src/GLModel.ts
> -                    if (bestlen > 0.1) {
You've removed the short circuiting of the loop so now it will run longer.  Why do you think this is an improvement?

2023-06-13 13:30 UTC, dkoes commented on src/GLDraw.ts
> +        const rot = new Float32Array([cosA, sinA, 0, -sinA * cosB, cosA * cosB, sinB, sinA * sinB, -cosA * sinB, cosB]);
Setting the values individually instead of allocating a list first is more than twice as fast (go ahead and run it through JSBench.Me)

2023-06-13 13:34 UTC, adithyaakrishna commented
@dkoes I completely understand, I will work on creating seperate PRs for the same. There were a couple of changes I had done, but these were without much understanding of the library. I will close this and create seperate ones as you suggested

2023-06-13 13:34 UTC, closed without merging