[Bug] - Fixed Caching of NPM Dependencies
3dmol/3Dmol.js pull request #675
Opened 2023-04-20 14:04 UTC by adithyaakrishna

**Description:**

The caching of npm dependencies was not working properly and upon going through the steps, found a couple of issues and fixed it with respect to this PR

2023-04-20 15:24 UTC, dkoes approved these changes

2023-04-20 15:25 UTC, dkoes requested changes
Tests are failing..

2023-05-20 15:33 UTC, adithyaakrishna commented
@dkoes I have also updated the node versions across the other workflows to make it consistent with https://github.com/3dmol/3Dmol.js/commit/ec8b26a44ef155995ec7c979e89a0d497ea37eb2

2023-05-20 23:52 UTC, dkoes approved these changes

2023-05-20 23:53 UTC, merged