Updated Types for Parsers and Parser Utils
3dmol/3Dmol.js pull request #699
Opened 2023-07-10 19:44 UTC by adithyaakrishna

**Description:**

This PR updates the types for Parsers and its utility functions

2023-07-10 20:00 UTC, adithyaakrishna commented
Parser Utils is giving a type error, will fix it first thing tomorrow morning :)

2023-07-13 08:20 UTC, adithyaakrishna commented
@dkoes Tests Passed 🎉

2023-07-13 15:38 UTC, dkoes requested changes
Put documentation back in.

2023-07-13 15:38 UTC, dkoes commented on src/parsers/PQR.ts
> -    /**
why are you removing documentation?

2023-07-13 15:38 UTC, dkoes commented on src/parsers/PRMTOP.ts
> -/**
do not remove documentation, the applies across the commit

2023-07-13 17:41 UTC, adithyaakrishna commented
@dkoes Thanks for pointing them out, I had missed reverting those changes back. I have updated the docs with the above commit

2023-07-13 18:58 UTC, dkoes approved these changes

2023-07-13 18:58 UTC, merged